#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : soundmodem
Version  : 0.20
Release  : 2
URL      : http://download.gna.org/soundmodem/soundmodem-0.20.tar.gz
Source0  : http://download.gna.org/soundmodem/soundmodem-0.20.tar.gz
Summary  : Driver and diagnostic utility for Usermode SoundModem
Group    : Development/Tools
License  : GPL-2.0
Requires: soundmodem-bin
Requires: soundmodem-locales
Requires: soundmodem-doc
BuildRequires : alsa-lib-dev
BuildRequires : pkgconfig(audiofile)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : util-linux-dev
Patch1: fix-ftbfs-gcc6-matlib-mdet.patch

%description
This package contains the driver and the diagnostic utility for
userspace SoundModem. It allows you to use soundcards supported
by OSS/Free as Amateur Packet Radio modems.

%package bin
Summary: bin components for the soundmodem package.
Group: Binaries

%description bin
bin components for the soundmodem package.


%package dev
Summary: dev components for the soundmodem package.
Group: Development
Requires: soundmodem-bin
Provides: soundmodem-devel

%description dev
dev components for the soundmodem package.


%package doc
Summary: doc components for the soundmodem package.
Group: Documentation

%description doc
doc components for the soundmodem package.


%package locales
Summary: locales components for the soundmodem package.
Group: Default

%description locales
locales components for the soundmodem package.


%prep
%setup -q -n soundmodem-0.20
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1507326253
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1507326253
rm -rf %{buildroot}
%make_install
%find_lang soundmodem

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/soundmodem
/usr/bin/soundmodemconfig

%files dev
%defattr(-,root,root,-)
/usr/include/*.h

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man8/*

%files locales -f soundmodem.lang
%defattr(-,root,root,-)

